### ISSUE TITLE
exceptions everywhere

### ISSUE THREAD

**Issue by kaeverens** [hellovoid/gdax#7]
The Guzzle dependency is throwing fatal exceptions everytime anything it doesn't like happens, and your script doesn't appear to handle these at all.

For example, if I create an order and use your script to check that order every second until it has filled, then if I go into the GDAX site by hand and cancel the order, the script will crash because Guzzle cries when it's not able to find the order.

Is there a way to make these exceptions less fatal? I mean, something as simple as returning false should be enough. it's not necessary to totally destroy the running instance just because the network is wobbly or because something is not where it was expected to be.

**Comment by hellovoid** [comment]
Take a look [HttpException.php](https://github.com/hellovoid/gdax/blob/master/src/Exception/HttpException.php)

[Example](https://github.com/hellovoid/gdax#cancel-an-order) with exception handling.

**Comment by kaeverens** [comment]
thank you. I'll try that and see if any crashes happen in the next few days :-)

**Comment by kaeverens** [comment]
no crashes up until a moment ago, when a 502 timeout on the GDAX server triggered a ServerException which was fatal even though it looks like it was caught by your exception wrapper.

Here's the error log:

```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `GET https://api.gdax.com/accounts` resulted in a `504 Gateway Time-out` response:
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class (truncated...)
 in /home/gdax/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/gdax/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/gdax/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/gdax/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/gdax/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /home/gdax/vendor/guzzlehttp/promises/src/Promise.php(246): Gu in /home/gdax/vendor/hellovoid/gdax/src/Exception/HttpException.php on line 29
```

**Comment by kaeverens** [comment]
the stack trace doesn't go all the way back to my code, but I think it might have been this segment:

```
    do {
      $ok=0;
      try {
        $accounts=$GLOBALS['client']->getAccounts();
        $ok=1;
      }
      catch (HttpException $e) {
        echo $e->getMessage()."\n";
        echo "will try again in 10s\n";
        sleep(10);
      }
    } while(!$ok);
```

**Comment by kaeverens** [comment]
and another one last night:

```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `GET https://api.gdax.com/products/LTC-EUR/ticker` resulted in a `504 Gateway Time-out` response:
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class (truncated...)
 in /home/gdax/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/gdax/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/gdax/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/gdax/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/gdax/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /home/gdax/vendor/guzzlehttp/promises/src/Promi in /home/gdax/vendor/hellovoid/gdax/src/Exception/HttpException.php on line 29
```

this was triggered in my own code from this:

```
      try {
        $history=$GLOBALS['client']->getProductHistoricRates($currency);
        $tick=$GLOBALS['client']->getProductTicker($currency);
        // more stuff (removed for clarity)
      }
      catch (HttpException $e) {
```

**Comment by kaeverens** [comment]
solved.

the issue was that I did not have the "use" command for the HttpException class

`use Hellovoid\Gdax\Exception\HttpException;
`
